config/routes.rb
Rails.application.routes.draw do
  root to: 'inicio#index' 

  get 'books/new', to: 'books#new'
  post 'books/notes/:id', to: 'books#create'
  get 'books/:id', to:'books#show'
  get 'books/:id/edit', to:'books#edit'
  patch 'books/:id/edit', to:'books#update', as: :book
  delete 'books/:id', to: 'books#destroy', as: :delete
  get 'books/user/:user_id', to: 'books#index'
  
  get 'books/:id/notes/new', to: 'notes#new', as: :new_notes
  post 'books/:id/notes/new', to: 'notes#create', as: :note_create
  patch 'books/:book_id/notes/:id', to: 'notes#update', as: :note_update
  delete 'books/:book_id/notes/:id', to: 'notes#destroy', as: :note_delete

  resources :books do
    resources :notes
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
end

  get 'inicio', to: 'inicio#index'

 devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
   
  end
end

app/models/note.rb
class Note < ApplicationRecord
has_rich_text :content
belongs_to :book
validates_length_of :title, maximum: 50, message: "-el nombre de la nota no puede superar los 30 caracteres"
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, except: [ :new, :create, :index]
  before_action :authenticate_user!

  def index
   
  end

  def show
  end

  def new
    @book = Book.find(params[:id])
    @note = Note.new
    @book.notes.build
    
  end
 
  def create
    @book = Book.find(params[:id])
    @note = @book.notes.create(title: params[:title],content: params[:content]) 
    if @note.save
      redirect_to  book_notes_path(@book.id)
    else
      render :new
    end

  end


  def edit
  end

  def update
    @note.update(title: params[:note][:title],content: params[:note][:content])
    @book = Book.find(params[:book_id])
    redirect_to book_notes_path(@book)
  end

  def destroy
    @note.destroy
    @book = Book.find(params[:book_id])
    redirect_to book_notes_path(@book)
  end

  def find_note
    @note = Note.find(params[:id])
  end
 
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<div style="display:inline-block">
<% @book = Book.find(params[:book_id])%>
<%= form_with(model: @note, url: note_update_path(@book.id, @note), method: "patch") do |form| %>
<div class="field">
    <div class="mb-3">
      <%= form.label :title, :class => "form-label"%>
      <%= form.text_field :title, :class => "form-control"%>
    </div>
    <div class="container box p-4">
      <div class="mb-3">
        <%= form.label :content, :class => "form-label" %>
        <%= form.rich_text_area :content %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= form.submit  :class => " btn btn-dark btn-block" %>
  </div>
<% end %>
</div>

app/views/notes/_note.html.erb
<div style="display:inline-block; margin:10px; padding:10px">
<div class="card" style="padding:15px; max-width:300px;">
<h3 class="text-uppercase"> <%= note.title %> </h3>
<p class="text-secondary"> <%= note.created_at %> </p>
<p> <%= note.content %> </p>
<%= link_to "Editar", edit_book_note_path(@book, note) %>
<%= link_to "Eliminar",note_delete_path(@book, note),
                  method: :delete,
                  data: { confirm: "Are you sure?" }  %>
</div>
</div>

app/views/notes/create.html.erb
<h1> entra a la vista create </h1>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
<div style="display:inline-block">
<p> Editar nota </p>
<%= render "notes/form" %>
</div>

app/views/notes/index.html.erb
<div style="display:inline-block">
<% @book = Book.find(params[:book_id]) %>
<h1> Notas del cuaderno <%= @book.title %> </h1> 
<%= render @book.notes %>
<%= link_to "Agregar nota", new_notes_path(@book) %>
</div>

app/views/notes/new.html.erb
<div style="display:inline-block">
<p> Crear nota </p>
<%= form_with do |form| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>
      <ul>
        <% @note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <div class="mb-3">
      <%= form.label :title, :class => "form-label"%>
      <%= form.text_field :title, :class => "form-control"%>
    </div>
    <div class="container box p-4">
      <div class="mb-3">
        <%= form.label :content, :class => "form-label" %>
        <%= form.rich_text_area :content %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= form.submit  :class => " btn btn-dark btn-block" %>
  </div>
<% end %>
</div>

app/views/notes/show.html.erb
<div style="display:inline-block">
<%= @note.content %>
</div>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>