config/routes.rb
Rails.application.routes.draw do
  root to: 'inicio#index' 

  get 'books/new', to: 'books#new'
  post 'books/notes/:id', to: 'books#create'
  get 'books/:id', to:'books#show'
  get 'books/:id/edit', to:'books#edit'
  patch 'books/:id/edit', to:'books#update', as: :book
  delete 'books/:id', to: 'books#destroy', as: :delete
  get 'books/user/:user_id', to: 'books#index'
  
  get 'books/:id/notes/new', to: 'notes#new', as: :new_notes
  post 'books/:id/notes/new', to: 'notes#create', as: :note_create
  patch 'books/:book_id/notes/:id', to: 'notes#update', as: :note_update
  delete 'books/:book_id/notes/:id', to: 'notes#destroy', as: :note_delete

  resources :books do
    resources :notes
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
end

  get 'inicio', to: 'inicio#index'

 devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
   
  end
end

app/models/book.rb
class Book < ApplicationRecord
        validates_uniqueness_of :title, scope: :user_id
        validates :title, presence: true
        validates_length_of :title, maximum: 30, message: "-El nombre del cuaderno no puede superar los 30 caracteres"
        belongs_to :user   
        has_many :notes, dependent: :destroy
        accepts_nested_attributes_for :notes
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, except: [:new, :create, :index]
    before_action :authenticate_user!

    def index
      @user = User.find(params[:user_id])
      
    end
  
    def new
      @book = Book.new
    end

    def create
      @book = current_user.books.create(title: params[:book][:title]) 
      if @book.save
        redirect_to books_path(:user_id => current_user.id)
      else
        render :new
      end
    end

    def edit
   
    end
  
    def update
      if (@book.title != "Global")
      @book.update(title: params[:book][:title])
      redirect_to books_path(:user_id => current_user.id)
      end
    end
  
    def destroy
      if (@book.title != "Global")
         @book.destroy
      end
      redirect_to books_path(:user_id => current_user.id)
    end
  
    def find_book
      @book = Book.find(params[:id])
    end

    private

    def books_params
      params.require(:book).permit(:title, notes_attributes: [:title, :content])
    end
  
   
  end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div style="display:inline-block">
<div class="card" style="padding:15px; max-width:300px;">
<h3 class="text-uppercase"> <%= book.title %> </h3>
<%= link_to "Editar", edit_book_path(book) %>
<%= link_to "Eliminar", delete_path(book),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
<%= link_to "Ver notas", book_notes_path(book) %>
<%= link_to "Agregar nota", new_notes_path(book) %>
</div>
</div >

app/views/books/_form.html.erb
<%= form_with(model:@book, local:true) do |f| %>
    <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    </div>
    <%= f.submit class: "btn btn-primary text-uppercase"%>
    <% end %>

app/views/books/create.html.erb
<h1> create </h1>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<div style="display:inline-block">
<p> Editar cuaderno </p>
<%= render "books/form" %>
</div>

app/views/books/index.html.erb
<div style="display:inline-block">
<h1> Mis cuadernos </h1>    

<%= render @user.books %>
</div>

app/views/books/new.html.erb
<div style="display:inline-block">
<p> Crear cuaderno </p>
<%= render "books/form" %>
</div>

app/views/books/show.html.erb
<h1> show </h1>

app/views/books/update.html.erb
<h1>El cuaderno Global no puede ser modificado ni eliminado</h1>